apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tvqyaq7cs-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a1edc06c9e.lfvr.p3.openshiftapps.com/rhtap/rhtap-qe:2a5e633e2fef1168b87bd7a7969100ca043ffd1d@sha256:18fdfbb632ea77e03c7c3603430cb89543076d1211deb783c0c251b6976389a7
          name: container-image
